In this notebook we are going to see some fundamentals of Python and of the related packages (Numpy, Scikit-learn, etc.) 

# Numbers

In [1]:
x = 1
print(x)

1


In Python 3 the division always returns a float

In [2]:
x = 3.0
y = 2.0
print(x/y)

1.5


In [3]:
x = 3
y = 2
z = x/y
print('value of x: ', x, ' type of x: ', type(x) )
print('value of z: ', z, ' type of z: ', type(z))

value of x:  3  type of x:  <class 'int'>
value of z:  1.5  type of z:  <class 'float'>


The // command performs integer division (in general notice the different behaviour of division in Python 2 and Python 3)

In [4]:
x = 3
y = 2
z = x // y
print('value of z: ', z, ' type of z: ', type(z))

x = 3.0
y = 2.0
z = x // y
print('value of z: ', z, ' type of z: ', type(z))

value of z:  1  type of z:  <class 'int'>
value of z:  1.0  type of z:  <class 'float'>


# Lists

The list is ordered and elements can be added and removed

In [5]:
a = [20, 2, -6]
print(a)
print(a[2])

[20, 2, -6]
-6


In [6]:
b = ['I','will','pass','ML']
print(b[1])

will


In [7]:
b = []
print(b)
b = list()
print(b)
b.append('I')
b.append('will')
b.append('pass')
b.append('ML')
print(b)
b.remove('ML')
print(b)

[]
[]
['I', 'will', 'pass', 'ML']
['I', 'will', 'pass']


range(start,end) creates an array with all the numbers from (start) to (end-1)

In [8]:
c = range(1,5)
print(c)
print(type(c))
print(list(c))

range(1, 5)
<class 'range'>
[1, 2, 3, 4]


":" indexing similar to Matlab (but notice that ending index value is not included)

In [9]:
d = [0,1,2,3,4,5,6,7,8,9]
print(d)
print(d[0:10])
print(d[:])
print(d[1:10])
print(d[0:9], 'last element is (end-1) !')
print(d[3:])
print(d[:7])
print(d[:-2])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8] last element is (end-1) !
[3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 7]


# Dictionaries

A dictionary is a collection which is unordered, changeable and indexed. In Python dictionaries are written with curly brackets, and they have keys and values.

In [10]:
name2grade = dict()
name2grade['Pietro'] = 22
name2grade['Umberto'] = 18
name2grade['Davide'] = 30
print(name2grade)

{'Pietro': 22, 'Umberto': 18, 'Davide': 30}


In [11]:
name2grade = {'Pietro': 22, 'Umberto': 18, 'Davide' : 30}
print(name2grade)

{'Pietro': 22, 'Umberto': 18, 'Davide': 30}


In [12]:
print(name2grade['Umberto'])

18


In [13]:
print(name2grade.keys())

dict_keys(['Pietro', 'Umberto', 'Davide'])


In [14]:
del name2grade['Umberto']
print(name2grade)

{'Pietro': 22, 'Davide': 30}


# Sets

Differently from lists sets have no order

In [5]:
a = set([0,1,2])
print(a)

{0, 1, 2}


In [6]:
a = list(['I','will','pass','ML'])
print(a)
b = set(a)
print('b contains:', b)

['I', 'will', 'pass', 'ML']
b contains: {'ML', 'pass', 'I', 'will'}


In [7]:
c = set(['I'])
c.add('hopefully')
c.add('maybe')
print('c contains:' , c)
c.remove('maybe')
print('c contains:' , c)

c contains: {'hopefully', 'I', 'maybe'}
c contains: {'hopefully', 'I'}


In [8]:
print(b.union(c))
print(b.intersection(c))
print(b.difference(c))

{'pass', 'will', 'ML', 'hopefully', 'I'}
{'I'}
{'ML', 'pass', 'will'}


# Tuple
A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Also notice that elements cannot be added or removed (it is immutable)

In [9]:
t = (5, 6) #tuple
print(t)
dt = dict()
l = list([5,6])
print(l)
dt[t]='ok'
print(dt)
print(dt[t])

(5, 6)
[5, 6]
{(5, 6): 'ok'}
ok


# If-then-else

In [10]:
x = 3
if x > 2:
    print('x > 2')
else:
    print('x <= 2')
print("The value of x is: " + str(x)) # + concatenate strings
print("The value of x is:" , x)

x > 2
The value of x is: 3
The value of x is: 3


In [11]:
c = 'Good Morning !!!'
if c != "hello":
    print("value of c: " + c)
else:
    print("c has value hello")

value of c: Good Morning !!!


In [22]:
x = 9.9
if (x > 0.0) and (x <10.0):
    print("x is between 0 and 10 (excluded)")
else:
    print("x <= 0 or x >= 10")

x is between 0 and 10 (excluded)


In [23]:
grade = 27.2
course = "Computer Vision"
if (grade > 26) and (not (course != "ML")):
    print("Everything is good")
else:
    print("Need to study for ML!!!")

Need to study for ML!!!


# Iterating over elements

In [24]:
x = list(['I','will','pass','ML'])
for elem in x:
    print(elem)

I
will
pass
ML


In [25]:
x = list(['I','will','pass','ML'])
print('Number of elements: ' , len(x))
for i in range(len(x)):
    print(x[i])

Number of elements:  4
I
will
pass
ML


In [26]:
d = dict()
d[30] = set(['Pietro','Davide'])
d[26] = set(['Umberto'])
keys = d.keys()
for key in keys:
             print("students with mark = "+str(key)+":")
             for elem in d[key]:
                 print(elem)

students with mark = 30:
Pietro
Davide
students with mark = 26:
Umberto


# Importing packages

In [27]:
import scipy as sp
import numpy as np
import sklearn as sl

# Arrays in numpy

In [28]:
#create vector given values in it
a = np.array([1.0, 2.0, 3.0])
print(a)
print(a.shape)
#create matrix  given values in it
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)
print(b.shape)
#create matrix of 0's of given size
c = np.zeros((3,2))
print(c)
#create matrix of size 1x3 (different from array of 3 elements!)
c1 = np.zeros((1,3))
c1[0,:] = [1, 2, 3]
print(c1)
print(c1.shape, 'notice the difference with the first example !!')
#create matrix of 1's of given size
d = np.ones((2,3))
print(d)
#create identity matrix of given size
e = np.eye(4)
print(e)
#create random matrix (values in [0,1]) of given size
f = np.random.random((2,4))
print(f)

[1. 2. 3.]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 2. 3.]]
(1, 3) notice the difference with the first example !!
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.92924144 0.15404071 0.16732908 0.73578268]
 [0.17745905 0.01095764 0.53876922 0.44743958]]


# Array indexing in numpy

In [63]:
e= np.array([[1,5,7,9],[2,6,8,10]]);
print(e[:,:])

[[ 1  5  7  9]
 [ 2  6  8 10]]


In [64]:
print(e[:,0:4])

[[ 1  5  7  9]
 [ 2  6  8 10]]


In [67]:
print(e[:,1])

[5 6]


In [68]:
print(e[:,1:3])

[[5 7]
 [6 8]]


In [69]:
print(e[:,1:1])

[]


In [70]:
print(e[:,1:-1])

[[5 7]
 [6 8]]


In [71]:
print(e[0,1:])

[5 7 9]


In [72]:
print(e[0,0:3])

[1 5 7]


# Reading from file

In [29]:
file_name = "data/marks.csv"
infile = open(file_name,'r')
line_c = 0
for line in infile:
    if line_c <=4:
        print(line)
    line_c += 1
infile.close()

1,23,21,20

2,28,30,29

3,25,20,29

4,27,30,29

5,18,22,26



In [12]:
file_name = "data/marks.csv"
infile = open(file_name,'r')
line_c = 0
for line in infile:
    if line_c <=4:
        print("Line:\n"+line)
        v = line.strip().split(',') #strip removes whitespaces and newlines characters
        print("List: "+str(v))
        print("Elements in list:")
        vv[line_c]=v
        for i in range(len(v)):
            print(v[i].strip()) #strip removes whitespaces
        print('\n\n')
    line_c += 1
infile.close()

print(v)

Line:
1,23,21,20

List: ['1', '23', '21', '20']
Elements in list:
1
23
21
20



Line:
2,28,30,29

List: ['2', '28', '30', '29']
Elements in list:
2
28
30
29



Line:
3,25,20,29

List: ['3', '25', '20', '29']
Elements in list:
3
25
20
29



Line:
4,27,30,29

List: ['4', '27', '30', '29']
Elements in list:
4
27
30
29



Line:
5,18,22,26

List: ['5', '18', '22', '26']
Elements in list:
5
18
22
26



['5', '18', '22', '26']


# Writing to file

In [31]:
infile_name = "data/marks.csv"
infile = open(file_name,'r')
line_c = 0
outfile_name = "tmp.txt"
outfile = open(outfile_name,'w')
for line in infile:
    if line_c <=4:
        outfile.write("Line:\n"+line+"\n")
        v = line.split(',')
        outfile.write("List: "+str(v)+"\n")
        outfile.write("Elements in list:\n")
        for i in range(len(v)):
            outfile.write(v[i].strip()+"\n")
    line_c += 1
infile.close()
outfile.write(str(10.))
outfile.close()

# Reading from CSV (Comma Separated Value) file

In [32]:
import csv

filename = "data/marks.csv"

lines = csv.reader(open(filename, newline=''), delimiter=',')

for line in lines:
    print(line)

['1', '23', '21', '20']
['2', '28', '30', '29']
['3', '25', '20', '29']
['4', '27', '30', '29']
['5', '18', '22', '26']
['6', '27', '22', '22']
['7', '25', '24', '23']
['8', '22', '23', '26']
['9', '21', '23', '22']
['10', '28', '30', '29']


In [33]:
import csv

filename = "data/marks.csv"

lines = csv.reader(open(filename, newline=''), delimiter=',')

dataset = list(lines)
for i in range(len(dataset)):
    dataset[i] = [float(x) for x in dataset[i]]
print(dataset)
print('Number of students:', len(dataset))

[[1.0, 23.0, 21.0, 20.0], [2.0, 28.0, 30.0, 29.0], [3.0, 25.0, 20.0, 29.0], [4.0, 27.0, 30.0, 29.0], [5.0, 18.0, 22.0, 26.0], [6.0, 27.0, 22.0, 22.0], [7.0, 25.0, 24.0, 23.0], [8.0, 22.0, 23.0, 26.0], [9.0, 21.0, 23.0, 22.0], [10.0, 28.0, 30.0, 29.0]]
Number of students: 10


# Functions

In [34]:
def print_value(x):
    print(str(x))

print_value(10)
print_value('hello')

10
hello


In [35]:
def sign(value):
    if value > 0:
        return 1.
    elif value < 0:
        return -1.
    else:
        return 0.

print(sign(10.2))
print(sign(-0.6))
print(sign(0))

1.0
-1.0
0.0


# Assignment

1) Load the provided .csv file with the used car data

2) Use a linear regression to estimate the car prices from the year, kilometers or engine power. You can make a simple 1D regression from each one of the parameters independently (as an optional task you can also try a 2D or 3D regression combining multiple cues)

3) Firstly perform the estimation using the scipy linregress function (or alternatively you can use the sklearn.linear_model.LinearRegression class)

4) Have a look at the correlation coefficient to see which of the 3 features works better

5) Then implement the least square algorithm: You should get exactly the same solution of linregress !

6) Plot the data and the lines representing the output of the linregress and least square algorithms